app = "depot-manager-fe-helbadao"
primary_region = "cdg"

[build.args]
  NEXT_PUBLIC_API_BASE = "https://depot-manager-be-helbadao.fly.dev"
  NEXT_PUBLIC_WS_BASE = "wss://depot-manager-be-helbadao.fly.dev"

[env]
  PORT = "3000"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
