app = "depot-manager-be-helbadao"
primary_region = "cdg"

[env]
  PORT = "8080"
  DB_PATH = "/data/pos.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

[[mounts]]
  source = "depot_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
